version: '3.1'
services:
  stats-server:
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:14-alpine
    container_name: stats_container
    ports:
      - "6541:5431"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root